import json
from pathlib import Path

def parse_block(block: str):
    mapping = {}
    for raw_line in block.strip().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#'):
            continue
        if '=' not in line:
            raise ValueError(f"Missing '=' in line: {raw_line!r}")
        key, value = line.split('=', 1)
        mapping[key.strip()] = value.strip()
    return mapping

zh_hans = parse_block('''
common.cancel=取消
common.done=完成
common.ok=好
history.empty.subtitle=记录一次会话即可在此查看。
history.empty.title=暂无会话
history.navigation.title=历史记录
insights.card.cumulativeGain.message.format=你已在 %@ 次会话中攀升 %@。
insights.card.cumulativeGain.title=累计攀升
insights.card.empty.message=开始第一次攀登以解锁气压洞察。
insights.card.empty.title=暂无会话
insights.card.lastSession.message.format=攀升了 %@，耗时 %@。
insights.card.lastSession.title=上一会话
insights.card.localPressure.message.format=%@ • %@ • %@
insights.card.localPressure.title=本地气压
insights.card.pressureTrend.title=气压趋势
insights.card.weeklyTrend.message.format=平均气压为 %@，每次会话变化 %@ kPa。
insights.card.weeklyTrend.title=每周趋势
insights.direction.dropping=下降中
insights.direction.rising=上升中
insights.navigation.title=洞察
insights.progress.weather=正在刷新天气
measure.action.calibrate=校准
measure.action.pause=暂停
measure.action.recording=正在记录…
measure.action.resume=继续
measure.action.start=开始会话
measure.action.stop=停止
measure.alert.barometerUnavailable.message=此设备不支持气压计传感器。
measure.alert.barometerUnavailable.title=无法使用气压计
measure.chart.axis.altitude.imperial=海拔 (英尺)
measure.chart.axis.altitude.metric=海拔 (米)
measure.chart.axis.pressure=气压
measure.chart.axis.time=时间
measure.chart.placeholder=点击“开始”即可在此查看实时读数。
measure.chart.selected=已选
measure.chart.selected.detail.format=%@ • %@
measure.chart.title.elevation=实时海拔
measure.chart.title.pressure=实时气压
measure.dialog.stop.title=要停止会话吗？
measure.dialog.stopAndSave=停止并保存
measure.hint.startAltimeter=点击“开始”以开始跟踪你的攀登。
measure.hint.startBarometer=点击“开始”以开始跟踪气压变化。
measure.metric.currentAltitude=当前海拔
measure.metric.currentPressure=当前气压
measure.metric.duration=时长
measure.metric.gain=上升
measure.metric.high=最高
measure.metric.loss=下降
measure.metric.low=最低
measure.pastSessions.title=以往会话
measure.sessionSummary.title=会话摘要
profile.about.appName=HowHigh
profile.about.version=初始版本
profile.action.applyPressure.accessibility=应用 WeatherKit 气压值
profile.action.applyPressure.format=应用 %@
profile.action.refreshWeather=从 WeatherKit 更新
profile.action.whatIsThis=这是什么？
profile.calibration.footer=海平面气压可优化海拔估算。典型值：101.3 kPa。
profile.info.description=调整此值以匹配附近气象站读数，从而获得更准确的海拔计算。
profile.info.tip.format=提示：搜索“%@ 海平面气压”或使用附近机场的 METAR 数据。
profile.info.title=海平面气压
profile.label.seaLevelPressure=海平面气压
profile.link.barometerTips=气压计传感器提示
profile.link.contactSupport=联系支持
profile.navigation.title=个人资料
profile.picker.units=首选单位
profile.region.unknown=您的区域
profile.section.about=关于
profile.section.calibration=校准
profile.section.support=支持
profile.section.units=单位
profile.section.weatherKit=WeatherKit 校准
profile.weatherKit.empty=获取本地气压以自动校准。
profile.weatherKit.latest=最新读数
profile.weatherKit.summary.format=%@ • %@ • %@
session.chart.axis.pressure=气压
session.chart.axis.time=时间
session.chart.placeholder=保存记录后会显示此图表。
session.chart.selected=无
session.chart.selected.detail.format=%@ • %@
session.chart.title.elevation=海拔
session.chart.title.pressure=气压
session.notes.placeholder=下一次冒险后添加备注，记录当时的环境。
session.notes.title=备注
session.overview.title=概览
tab.altimeter.title=高度计
tab.barometer.title=气压计
tab.profile.title=个人资料
trend.description.falling=气压下降
trend.description.rising=气压上升
trend.description.steady=气压稳定
units.imperial=英制 (英尺)
units.metric=公制 (米)
''')

ja = parse_block('''
common.cancel=キャンセル
common.done=完了
common.ok=OK
history.empty.subtitle=セッションを記録するとここに表示されます。
history.empty.title=セッションはまだありません
history.navigation.title=履歴
insights.card.cumulativeGain.message.format=%@ セッションで合計 %@ 登りました。
insights.card.cumulativeGain.title=累積獲得高度
insights.card.empty.message=最初の計測を始めて気圧のインサイトを確認しましょう。
insights.card.empty.title=セッションはまだありません
insights.card.lastSession.message.format=%@ で %@ を獲得しました。
insights.card.lastSession.title=前回のセッション
insights.card.localPressure.message.format=%@ • %@ • %@
insights.card.localPressure.title=ローカル気圧
insights.card.pressureTrend.title=気圧の傾向
insights.card.weeklyTrend.message.format=平均気圧は %@ 、セッションあたり %@ kPa 変化しています。
insights.card.weeklyTrend.title=週間傾向
insights.direction.dropping=低下中
insights.direction.rising=上昇中
insights.navigation.title=インサイト
insights.progress.weather=天気を更新中
measure.action.calibrate=校正
measure.action.pause=一時停止
measure.action.recording=記録中…
measure.action.resume=再開
measure.action.start=セッション開始
measure.action.stop=停止
measure.alert.barometerUnavailable.message=このデバイスには気圧センサーが搭載されていません。
measure.alert.barometerUnavailable.title=気圧計を利用できません
measure.chart.axis.altitude.imperial=高度 (ft)
measure.chart.axis.altitude.metric=高度 (m)
measure.chart.axis.pressure=気圧
measure.chart.axis.time=時間
measure.chart.placeholder=開始をタップするとここにライブデータが表示されます。
measure.chart.selected=選択済み
measure.chart.selected.detail.format=%@ • %@
measure.chart.title.elevation=ライブ高度
measure.chart.title.pressure=ライブ気圧
measure.dialog.stop.title=セッションを停止しますか？
measure.dialog.stopAndSave=停止して保存
measure.hint.startAltimeter=開始をタップして登高の追跡を始めましょう。
measure.hint.startBarometer=開始をタップして気圧変化の計測を始めましょう。
measure.metric.currentAltitude=現在の高度
measure.metric.currentPressure=現在の気圧
measure.metric.duration=経過時間
measure.metric.gain=上昇量
measure.metric.high=最高値
measure.metric.loss=下降量
measure.metric.low=最小値
measure.pastSessions.title=過去のセッション
measure.sessionSummary.title=セッション概要
profile.about.appName=HowHigh
profile.about.version=初回リリース
profile.action.applyPressure.accessibility=WeatherKit の気圧値を適用
profile.action.applyPressure.format=%@ を適用
profile.action.refreshWeather=WeatherKit から更新
profile.action.whatIsThis=これは何ですか？
profile.calibration.footer=海面気圧を設定すると高度推定が改善されます。標準値: 101.3 kPa。
profile.info.description=より正確な高度計算のために、近隣の観測値に合わせて調整してください。
profile.info.tip.format=ヒント：「%@ 海面気圧」で検索するか、近くの空港の METAR データを利用しましょう。
profile.info.title=海面気圧
profile.label.seaLevelPressure=海面気圧
profile.link.barometerTips=気圧センサーのヒント
profile.link.contactSupport=サポートに連絡
profile.navigation.title=プロフィール
profile.picker.units=使用する単位
profile.region.unknown=お住まいの地域
profile.section.about=概要
profile.section.calibration=校正
profile.section.support=サポート
profile.section.units=単位
profile.section.weatherKit=WeatherKit 校正
profile.weatherKit.empty=ローカル気圧を取得して自動校正します。
profile.weatherKit.latest=最新の読み取り
profile.weatherKit.summary.format=%@ • %@ • %@
session.chart.axis.pressure=気圧
session.chart.axis.time=時間
session.chart.placeholder=録画を保存するとグラフが表示されます。
session.chart.selected=なし
session.chart.selected.detail.format=%@ • %@
session.chart.title.elevation=高度
session.chart.title.pressure=気圧
session.notes.placeholder=次のアクティビティ後に条件を覚えておけるようメモを追加しましょう。
session.notes.title=メモ
session.overview.title=概要
tab.altimeter.title=高度計
tab.barometer.title=気圧計
tab.profile.title=プロフィール
trend.description.falling=気圧が低下しています
trend.description.rising=気圧が上昇しています
trend.description.steady=気圧は安定しています
units.imperial=ヤード・ポンド法 (ft)
units.metric=メートル法 (m)
''')

ko = parse_block('''
common.cancel=취소
common.done=완료
common.ok=확인
history.empty.subtitle=세션을 기록하면 여기에 표시됩니다.
history.empty.title=세션이 없습니다
history.navigation.title=기록
insights.card.cumulativeGain.message.format=%@회 세션에서 총 %@을(를) 올랐습니다.
insights.card.cumulativeGain.title=누적 상승 고도
insights.card.empty.message=첫 세션을 시작해 기압 인사이트를 확인하세요.
insights.card.empty.title=세션이 없습니다
insights.card.lastSession.message.format=%@ 동안 %@을(를) 획득했습니다.
insights.card.lastSession.title=마지막 세션
insights.card.localPressure.message.format=%@ • %@ • %@
insights.card.localPressure.title=지역 기압
insights.card.pressureTrend.title=기압 추세
insights.card.weeklyTrend.message.format=평균 기압은 %@이며 세션당 %@ kPa 변합니다.
insights.card.weeklyTrend.title=주간 추세
insights.direction.dropping=하락 중
insights.direction.rising=상승 중
insights.navigation.title=인사이트
insights.progress.weather=날씨 새로 고치는 중
measure.action.calibrate=보정
measure.action.pause=일시 중지
measure.action.recording=기록 중…
measure.action.resume=재개
measure.action.start=세션 시작
measure.action.stop=중지
measure.alert.barometerUnavailable.message=이 기기에는 기압 센서가 없습니다.
measure.alert.barometerUnavailable.title=기압계 사용 불가
measure.chart.axis.altitude.imperial=고도 (ft)
measure.chart.axis.altitude.metric=고도 (m)
measure.chart.axis.pressure=기압
measure.chart.axis.time=시간
measure.chart.placeholder=시작을 누르면 여기에서 실시간 데이터를 볼 수 있습니다.
measure.chart.selected=선택됨
measure.chart.selected.detail.format=%@ • %@
measure.chart.title.elevation=실시간 고도
measure.chart.title.pressure=실시간 기압
measure.dialog.stop.title=세션을 중지할까요?
measure.dialog.stopAndSave=중지 및 저장
measure.hint.startAltimeter=시작을 눌러 등반 추적을 시작하세요.
measure.hint.startBarometer=시작을 눌러 기압 변화를 기록하세요.
measure.metric.currentAltitude=현재 고도
measure.metric.currentPressure=현재 기압
measure.metric.duration=지속 시간
measure.metric.gain=상승
measure.metric.high=최고
measure.metric.loss=하강
measure.metric.low=최저
measure.pastSessions.title=지난 세션
measure.sessionSummary.title=세션 요약
profile.about.appName=HowHigh
profile.about.version=첫 번째 출시
profile.action.applyPressure.accessibility=WeatherKit 기압 값 적용
profile.action.applyPressure.format=%@ 적용
profile.action.refreshWeather=WeatherKit에서 업데이트
profile.action.whatIsThis=이게 무엇인가요?
profile.calibration.footer=해수면 기압을 설정하면 고도 추정이 향상됩니다. 일반 값: 101.3 kPa.
profile.info.description=근처 기상 관측값에 맞춰 조정하면 고도 계산이 더 정확해집니다.
profile.info.tip.format=팁: "%@ 해수면 기압"을 검색하거나 가까운 공항의 METAR 데이터를 사용하세요.
profile.info.title=해수면 기압
profile.label.seaLevelPressure=해수면 기압
profile.link.barometerTips=기압 센서 팁
profile.link.contactSupport=지원 문의
profile.navigation.title=프로필
profile.picker.units=선호 단위
profile.region.unknown=사용자 지역
profile.section.about=정보
profile.section.calibration=보정
profile.section.support=지원
profile.section.units=단위
profile.section.weatherKit=WeatherKit 보정
profile.weatherKit.empty=지역 기압을 가져와 자동으로 보정하세요.
profile.weatherKit.latest=최신 측정
profile.weatherKit.summary.format=%@ • %@ • %@
session.chart.axis.pressure=기압
session.chart.axis.time=시간
session.chart.placeholder=기록을 저장하면 그래프가 표시됩니다.
session.chart.selected=없음
session.chart.selected.detail.format=%@ • %@
session.chart.title.elevation=고도
session.chart.title.pressure=기압
session.notes.placeholder=다음 활동 후 조건을 기억하도록 메모를 추가하세요.
session.notes.title=메모
session.overview.title=개요
tab.altimeter.title=고도계
tab.barometer.title=기압계
tab.profile.title=프로필
trend.description.falling=기압이 하락하고 있습니다
trend.description.rising=기압이 상승하고 있습니다
trend.description.steady=기압이 안정적입니다
units.imperial=야드파운드법 (ft)
units.metric=미터법 (m)
''')

de = parse_block('''
common.cancel=Abbrechen
common.done=Fertig
common.ok=OK
history.empty.subtitle=Nimm eine Sitzung auf, um sie hier zu sehen.
history.empty.title=Noch keine Sitzungen
history.navigation.title=Verlauf
insights.card.cumulativeGain.message.format=Du bist %@ in %@ Sitzungen gestiegen.
insights.card.cumulativeGain.title=Kumulativer Anstieg
insights.card.empty.message=Starte deine erste Tour, um Druckanalysen freizuschalten.
insights.card.empty.title=Noch keine Sitzungen
insights.card.lastSession.message.format=Du hast %@ in %@ erreicht.
insights.card.lastSession.title=Letzte Sitzung
insights.card.localPressure.message.format=%@ • %@ • %@
insights.card.localPressure.title=Luftdruck vor Ort
insights.card.pressureTrend.title=Drucktrend
insights.card.weeklyTrend.message.format=Der Durchschnittsdruck liegt bei %@ und ändert sich um %@ kPa pro Sitzung.
insights.card.weeklyTrend.title=Wochentrend
insights.direction.dropping=fallend
insights.direction.rising=steigend
insights.navigation.title=Einblicke
insights.progress.weather=Wetter wird aktualisiert
measure.action.calibrate=Kalibrieren
measure.action.pause=Pause
measure.action.recording=Aufnahme…
measure.action.resume=Fortsetzen
measure.action.start=Sitzung starten
measure.action.stop=Stopp
measure.alert.barometerUnavailable.message=Dieses Gerät verfügt über keinen Barometersensor.
measure.alert.barometerUnavailable.title=Barometer nicht verfügbar
measure.chart.axis.altitude.imperial=Höhe (ft)
measure.chart.axis.altitude.metric=Höhe (m)
measure.chart.axis.pressure=Druck
measure.chart.axis.time=Zeit
measure.chart.placeholder=Tippe auf Start, um hier Live-Werte zu sehen.
measure.chart.selected=Ausgewählt
measure.chart.selected.detail.format=%@ • %@
measure.chart.title.elevation=Live-Höhe
measure.chart.title.pressure=Live-Druck
measure.dialog.stop.title=Sitzung beenden?
measure.dialog.stopAndSave=Beenden & sichern
measure.hint.startAltimeter=Tippe auf Start, um deinen Aufstieg zu verfolgen.
measure.hint.startBarometer=Tippe auf Start, um Druckänderungen zu verfolgen.
measure.metric.currentAltitude=Aktuelle Höhe
measure.metric.currentPressure=Aktueller Druck
measure.metric.duration=Dauer
measure.metric.gain=Anstieg
measure.metric.high=Maximum
measure.metric.loss=Abstieg
measure.metric.low=Minimum
measure.pastSessions.title=Frühere Sitzungen
measure.sessionSummary.title=Sitzungsübersicht
profile.about.appName=HowHigh
profile.about.version=Erstveröffentlichung
profile.action.applyPressure.accessibility=WeatherKit-Druckwert anwenden
profile.action.applyPressure.format=%@ anwenden
profile.action.refreshWeather=Über WeatherKit aktualisieren
profile.action.whatIsThis=Was ist das?
profile.calibration.footer=Der Luftdruck auf Meereshöhe verbessert die Höhenberechnung. Typischer Wert: 101,3 kPa.
profile.info.description=Passe den Wert an eine nahe Wetterstation an, um genauere Höhenangaben zu erhalten.
profile.info.tip.format=Tipp: Suche nach „%@ Luftdruck Meereshöhe“ oder nutze METAR-Daten des nächsten Flughafens.
profile.info.title=Luftdruck auf Meereshöhe
profile.label.seaLevelPressure=Luftdruck auf Meereshöhe
profile.link.barometerTips=Tipps zum Barometersensor
profile.link.contactSupport=Support kontaktieren
profile.navigation.title=Profil
profile.picker.units=Bevorzugte Einheiten
profile.region.unknown=deiner Region
profile.section.about=Info
profile.section.calibration=Kalibrierung
profile.section.support=Support
profile.section.units=Einheiten
profile.section.weatherKit=WeatherKit-Kalibrierung
profile.weatherKit.empty=Hole lokale Druckdaten für eine automatische Kalibrierung.
profile.weatherKit.latest=Letzte Messung
profile.weatherKit.summary.format=%@ • %@ • %@
session.chart.axis.pressure=Druck
session.chart.axis.time=Zeit
session.chart.placeholder=Dieses Diagramm erscheint, nachdem du eine Aufzeichnung gespeichert hast.
session.chart.selected=Keine
session.chart.selected.detail.format=%@ • %@
session.chart.title.elevation=Höhe
session.chart.title.pressure=Druck
session.notes.placeholder=Füge nach deinem nächsten Abenteuer Notizen hinzu, um die Bedingungen festzuhalten.
session.notes.title=Notizen
session.overview.title=Übersicht
tab.altimeter.title=Höhenmesser
tab.barometer.title=Barometer
tab.profile.title=Profil
trend.description.falling=Druck fällt
trend.description.rising=Druck steigt
trend.description.steady=Druck bleibt stabil
units.imperial=Imperial (ft)
units.metric=Metrisch (m)
''')

fr = parse_block('''
common.cancel=Annuler
common.done=Terminé
common.ok=OK
history.empty.subtitle=Enregistrez une session pour la voir ici.
history.empty.title=Aucune session
history.navigation.title=Historique
insights.card.cumulativeGain.message.format=Vous avez gravi %@ au cours de %@ sessions.
insights.card.cumulativeGain.title=Gain cumulé
insights.card.empty.message=Lancez votre première ascension pour afficher les informations de pression.
insights.card.empty.title=Aucune session
insights.card.lastSession.message.format=Gain de %@ en %@.
insights.card.lastSession.title=Dernière session
insights.card.localPressure.message.format=%@ • %@ • %@
insights.card.localPressure.title=Pression locale
insights.card.pressureTrend.title=Tendance de pression
insights.card.weeklyTrend.message.format=La pression moyenne est de %@ avec une variation de %@ kPa par session.
insights.card.weeklyTrend.title=Tendance hebdomadaire
insights.direction.dropping=en baisse
insights.direction.rising=en hausse
insights.navigation.title=Aperçus
insights.progress.weather=Actualisation météo
measure.action.calibrate=Calibrer
measure.action.pause=Pause
measure.action.recording=Enregistrement…
measure.action.resume=Reprendre
measure.action.start=Démarrer la session
measure.action.stop=Arrêter
measure.alert.barometerUnavailable.message=Ce dispositif ne possède pas de capteur barométrique.
measure.alert.barometerUnavailable.title=Baromètre indisponible
measure.chart.axis.altitude.imperial=Altitude (ft)
measure.chart.axis.altitude.metric=Altitude (m)
measure.chart.axis.pressure=Pression
measure.chart.axis.time=Temps
measure.chart.placeholder=Touchez Démarrer pour afficher ici les mesures en direct.
measure.chart.selected=Sélectionné
measure.chart.selected.detail.format=%@ • %@
measure.chart.title.elevation=Altitude en direct
measure.chart.title.pressure=Pression en direct
measure.dialog.stop.title=Arrêter la session ?
measure.dialog.stopAndSave=Arrêter et enregistrer
measure.hint.startAltimeter=Touchez Démarrer pour suivre votre ascension.
measure.hint.startBarometer=Touchez Démarrer pour suivre les variations de pression.
measure.metric.currentAltitude=Altitude actuelle
measure.metric.currentPressure=Pression actuelle
measure.metric.duration=Durée
measure.metric.gain=Gain
measure.metric.high=Maximum
measure.metric.loss=Perte
measure.metric.low=Minimum
measure.pastSessions.title=Sessions précédentes
measure.sessionSummary.title=Résumé de session
profile.about.appName=HowHigh
profile.about.version=Version initiale
profile.action.applyPressure.accessibility=Appliquer la valeur de pression WeatherKit
profile.action.applyPressure.format=Appliquer %@
profile.action.refreshWeather=Mettre à jour via WeatherKit
profile.action.whatIsThis=Qu'est-ce que c'est ?
profile.calibration.footer=La pression au niveau de la mer affine l'estimation de l'altitude. Valeur typique : 101,3 kPa.
profile.info.description=Ajustez cette valeur selon une station météo locale pour améliorer la précision de l'altitude.
profile.info.tip.format=Astuce : recherchez « %@ pression au niveau de la mer » ou utilisez les données METAR d'un aéroport proche.
profile.info.title=Pression au niveau de la mer
profile.label.seaLevelPressure=Pression au niveau de la mer
profile.link.barometerTips=Conseils pour le capteur barométrique
profile.link.contactSupport=Contacter l'assistance
profile.navigation.title=Profil
profile.picker.units=Unités préférées
profile.region.unknown=votre région
profile.section.about=À propos
profile.section.calibration=Calibrage
profile.section.support=Assistance
profile.section.units=Unités
profile.section.weatherKit=Calibrage WeatherKit
profile.weatherKit.empty=Récupérez la pression locale pour calibrer automatiquement.
profile.weatherKit.latest=Dernière lecture
profile.weatherKit.summary.format=%@ • %@ • %@
session.chart.axis.pressure=Pression
session.chart.axis.time=Temps
session.chart.placeholder=Ce graphique apparaîtra après l'enregistrement d'une session.
session.chart.selected=Aucune
session.chart.selected.detail.format=%@ • %@
session.chart.title.elevation=Altitude
session.chart.title.pressure=Pression
session.notes.placeholder=Ajoutez des notes après votre prochaine sortie pour garder en mémoire les conditions.
session.notes.title=Notes
session.overview.title=Vue d'ensemble
tab.altimeter.title=Altimètre
tab.barometer.title=Baromètre
tab.profile.title=Profil
trend.description.falling=Pression en baisse
trend.description.rising=Pression en hausse
trend.description.steady=Pression stable
units.imperial=Impérial (ft)
units.metric=Métrique (m)
''')

pt_br = parse_block('''
common.cancel=Cancelar
common.done=Concluído
common.ok=OK
history.empty.subtitle=Grave uma sessão para vê-la aqui.
history.empty.title=Nenhuma sessão ainda
history.navigation.title=Histórico
insights.card.cumulativeGain.message.format=Você subiu %@ em %@ sessões.
insights.card.cumulativeGain.title=Ganho acumulado
insights.card.empty.message=Inicie sua primeira medição para liberar insights de pressão.
insights.card.empty.title=Nenhuma sessão ainda
insights.card.lastSession.message.format=Você ganhou %@ em %@.
insights.card.lastSession.title=Última sessão
insights.card.localPressure.message.format=%@ • %@ • %@
insights.card.localPressure.title=Pressão local
insights.card.pressureTrend.title=Tendência de pressão
insights.card.weeklyTrend.message.format=A pressão média é %@ com variação de %@ kPa por sessão.
insights.card.weeklyTrend.title=Tendência semanal
insights.direction.dropping=em queda
insights.direction.rising=em alta
insights.navigation.title=Insights
insights.progress.weather=Atualizando dados do tempo
measure.action.calibrate=Calibrar
measure.action.pause=Pausar
measure.action.recording=Gravando…
measure.action.resume=Retomar
measure.action.start=Iniciar sessão
measure.action.stop=Parar
measure.alert.barometerUnavailable.message=Este dispositivo não possui sensor barométrico.
measure.alert.barometerUnavailable.title=Barômetro indisponível
measure.chart.axis.altitude.imperial=Altitude (ft)
measure.chart.axis.altitude.metric=Altitude (m)
measure.chart.axis.pressure=Pressão
measure.chart.axis.time=Tempo
measure.chart.placeholder=Toque em Iniciar para ver as leituras em tempo real aqui.
measure.chart.selected=Selecionado
measure.chart.selected.detail.format=%@ • %@
measure.chart.title.elevation=Altitude em tempo real
measure.chart.title.pressure=Pressão em tempo real
measure.dialog.stop.title=Parar a sessão?
measure.dialog.stopAndSave=Parar e salvar
measure.hint.startAltimeter=Toque em Iniciar para começar a rastrear sua subida.
measure.hint.startBarometer=Toque em Iniciar para registrar as mudanças de pressão.
measure.metric.currentAltitude=Altitude atual
measure.metric.currentPressure=Pressão atual
measure.metric.duration=Duração
measure.metric.gain=Ganho
measure.metric.high=Máximo
measure.metric.loss=Perda
measure.metric.low=Mínimo
measure.pastSessions.title=Sessões anteriores
measure.sessionSummary.title=Resumo da sessão
profile.about.appName=HowHigh
profile.about.version=Lançamento inicial
profile.action.applyPressure.accessibility=Aplicar valor de pressão do WeatherKit
profile.action.applyPressure.format=Aplicar %@
profile.action.refreshWeather=Atualizar pelo WeatherKit
profile.action.whatIsThis=O que é isso?
profile.calibration.footer=A pressão ao nível do mar melhora a estimativa de altitude. Valor típico: 101,3 kPa.
profile.info.description=Ajuste este valor para coincidir com as leituras de estações meteorológicas locais e obter altitudes mais precisas.
profile.info.tip.format=Dica: pesquise “%@ pressão ao nível do mar” ou use os dados METAR do aeroporto mais próximo.
profile.info.title=Pressão ao nível do mar
profile.label.seaLevelPressure=Pressão ao nível do mar
profile.link.barometerTips=Dicas do sensor barométrico
profile.link.contactSupport=Falar com o suporte
profile.navigation.title=Perfil
profile.picker.units=Unidades preferidas
profile.region.unknown=sua região
profile.section.about=Sobre
profile.section.calibration=Calibração
profile.section.support=Suporte
profile.section.units=Unidades
profile.section.weatherKit=Calibração WeatherKit
profile.weatherKit.empty=Busque a pressão local para calibrar automaticamente.
profile.weatherKit.latest=Última leitura
profile.weatherKit.summary.format=%@ • %@ • %@
session.chart.axis.pressure=Pressão
session.chart.axis.time=Tempo
session.chart.placeholder=Este gráfico aparecerá depois que você salvar uma gravação.
session.chart.selected=Nenhum
session.chart.selected.detail.format=%@ • %@
session.chart.title.elevation=Altitude
session.chart.title.pressure=Pressão
session.notes.placeholder=Adicione notas depois da próxima atividade para lembrar das condições.
session.notes.title=Notas
session.overview.title=Visão geral
tab.altimeter.title=Altímetro
tab.barometer.title=Barômetro
tab.profile.title=Perfil
trend.description.falling=Pressão em queda
trend.description.rising=Pressão em alta
trend.description.steady=Pressão estável
units.imperial=Imperial (ft)
units.metric=Métrico (m)
''')

ru = parse_block('''
common.cancel=Отмена
common.done=Готово
common.ok=ОК
history.empty.subtitle=Запишите сеанс, чтобы увидеть его здесь.
history.empty.title=Сеансов пока нет
history.navigation.title=История
insights.card.cumulativeGain.message.format=Вы поднялись на %@ за %@ сеансов.
insights.card.cumulativeGain.title=Совокупный подъём
insights.card.empty.message=Начните первый подъём, чтобы открыть данные о давлении.
insights.card.empty.title=Сеансов пока нет
insights.card.lastSession.message.format=Подъём %@ за %@.
insights.card.lastSession.title=Последний сеанс
insights.card.localPressure.message.format=%@ • %@ • %@
insights.card.localPressure.title=Местное давление
insights.card.pressureTrend.title=Тренд давления
insights.card.weeklyTrend.message.format=Среднее давление %@, изменение %@ кПа за сеанс.
insights.card.weeklyTrend.title=Недельный тренд
insights.direction.dropping=понижается
insights.direction.rising=повышается
insights.navigation.title=Аналитика
insights.progress.weather=Обновление данных погоды
measure.action.calibrate=Калибровать
measure.action.pause=Пауза
measure.action.recording=Запись…
measure.action.resume=Продолжить
measure.action.start=Начать сеанс
measure.action.stop=Стоп
measure.alert.barometerUnavailable.message=На этом устройстве нет барометрического датчика.
measure.alert.barometerUnavailable.title=Барометр недоступен
measure.chart.axis.altitude.imperial=Высота (фт)
measure.chart.axis.altitude.metric=Высота (м)
measure.chart.axis.pressure=Давление
measure.chart.axis.time=Время
measure.chart.placeholder=Нажмите «Пуск», чтобы видеть здесь показания в реальном времени.
measure.chart.selected=Выбрано
measure.chart.selected.detail.format=%@ • %@
measure.chart.title.elevation=Текущая высота
measure.chart.title.pressure=Текущее давление
measure.dialog.stop.title=Остановить сеанс?
measure.dialog.stopAndSave=Остановить и сохранить
measure.hint.startAltimeter=Нажмите «Пуск», чтобы начать отслеживать подъём.
measure.hint.startBarometer=Нажмите «Пуск», чтобы отслеживать изменения давления.
measure.metric.currentAltitude=Текущая высота
measure.metric.currentPressure=Текущее давление
measure.metric.duration=Длительность
measure.metric.gain=Подъём
measure.metric.high=Максимум
measure.metric.loss=Спуск
measure.metric.low=Минимум
measure.pastSessions.title=Прошлые сеансы
measure.sessionSummary.title=Сводка сеанса
profile.about.appName=HowHigh
profile.about.version=Первый релиз
profile.action.applyPressure.accessibility=Применить значение давления из WeatherKit
profile.action.applyPressure.format=Применить %@
profile.action.refreshWeather=Обновить через WeatherKit
profile.action.whatIsThis=Что это?
profile.calibration.footer=Давление на уровне моря улучшает расчёт высоты. Типичное значение: 101,3 кПа.
profile.info.description=Настройте этот параметр по данным ближайшей метеостанции для большей точности.
profile.info.tip.format=Совет: найдите «%@ давление на уровне моря» или используйте METAR ближайшего аэропорта.
profile.info.title=Давление на уровне моря
profile.label.seaLevelPressure=Давление на уровне моря
profile.link.barometerTips=Советы по датчику барометра
profile.link.contactSupport=Связаться с поддержкой
profile.navigation.title=Профиль
profile.picker.units=Предпочитаемые единицы
profile.region.unknown=вашем регионе
profile.section.about=О приложении
profile.section.calibration=Калибровка
profile.section.support=Поддержка
profile.section.units=Единицы
profile.section.weatherKit=Калибровка WeatherKit
profile.weatherKit.empty=Получите местное давление для автоматической калибровки.
profile.weatherKit.latest=Последнее измерение
profile.weatherKit.summary.format=%@ • %@ • %@
session.chart.axis.pressure=Давление
session.chart.axis.time=Время
session.chart.placeholder=Диаграмма появится после сохранения записи.
session.chart.selected=Нет
session.chart.selected.detail.format=%@ • %@
session.chart.title.elevation=Высота
session.chart.title.pressure=Давление
session.notes.placeholder=Добавьте заметки после следующего выхода, чтобы помнить условия.
session.notes.title=Заметки
session.overview.title=Обзор
tab.altimeter.title=Высотомер
tab.barometer.title=Барометр
tab.profile.title=Профиль
trend.description.falling=Давление падает
trend.description.rising=Давление растёт
trend.description.steady=Давление стабильное
units.imperial=Британская система (ft)
units.metric=Метрическая (m)
''')

ar = parse_block('''
common.cancel=إلغاء
common.done=تم
common.ok=حسنًا
history.empty.subtitle=سجّل جلسة لتظهر هنا.
history.empty.title=لا توجد جلسات بعد
history.navigation.title=السجل
insights.card.cumulativeGain.message.format=صعدت %@ عبر %@ جلسات.
insights.card.cumulativeGain.title=إجمالي الارتفاع
insights.card.empty.message=ابدأ أول صعود لك لعرض رؤى الضغط.
insights.card.empty.title=لا توجد جلسات بعد
insights.card.lastSession.message.format=حققت %@ خلال %@.
insights.card.lastSession.title=الجلسة الأخيرة
insights.card.localPressure.message.format=%@ • %@ • %@
insights.card.localPressure.title=الضغط المحلي
insights.card.pressureTrend.title=اتجاه الضغط
insights.card.weeklyTrend.message.format=متوسط الضغط %@ ويتغير بمقدار %@ كيلو باسكال لكل جلسة.
insights.card.weeklyTrend.title=اتجاه أسبوعي
insights.direction.dropping=ينخفض
insights.direction.rising=يرتفع
insights.navigation.title=الرؤى
insights.progress.weather=جارٍ تحديث الطقس
measure.action.calibrate=معايرة
measure.action.pause=إيقاف مؤقت
measure.action.recording=جارٍ التسجيل…
measure.action.resume=استئناف
measure.action.start=بدء الجلسة
measure.action.stop=إيقاف
measure.alert.barometerUnavailable.message=لا يتوفر مستشعر للضغط الجوي على هذا الجهاز.
measure.alert.barometerUnavailable.title=البارومتر غير متاح
measure.chart.axis.altitude.imperial=الارتفاع (قدم)
measure.chart.axis.altitude.metric=الارتفاع (متر)
measure.chart.axis.pressure=الضغط
measure.chart.axis.time=الوقت
measure.chart.placeholder=اضغط على بدء لعرض القراءات الحية هنا.
measure.chart.selected=محدد
measure.chart.selected.detail.format=%@ • %@
measure.chart.title.elevation=ارتفاع مباشر
measure.chart.title.pressure=ضغط مباشر
measure.dialog.stop.title=هل تريد إنهاء الجلسة؟
measure.dialog.stopAndSave=إيقاف وحفظ
measure.hint.startAltimeter=اضغط على بدء لبدء تتبع صعودك.
measure.hint.startBarometer=اضغط على بدء لبدء تتبع تغيّر الضغط.
measure.metric.currentAltitude=الارتفاع الحالي
measure.metric.currentPressure=الضغط الحالي
measure.metric.duration=المدة
measure.metric.gain=ارتفاع
measure.metric.high=أعلى قيمة
measure.metric.loss=انخفاض
measure.metric.low=أدنى قيمة
measure.pastSessions.title=الجلسات السابقة
measure.sessionSummary.title=ملخص الجلسة
profile.about.appName=HowHigh
profile.about.version=الإصدار الأول
profile.action.applyPressure.accessibility=تطبيق قيمة الضغط من WeatherKit
profile.action.applyPressure.format=تطبيق %@
profile.action.refreshWeather=تحديث من WeatherKit
profile.action.whatIsThis=ما هذا؟
profile.calibration.footer=يضبط الضغط عند مستوى سطح البحر تقديرات الارتفاع. القيمة النموذجية: 101.3 كيلو باسكال.
profile.info.description=اضبط هذه القيمة لتطابق قراءات محطة الطقس القريبة للحصول على قياسات ارتفاع أدق.
profile.info.tip.format=نصيحة: ابحث عن "ضغط %@ عند مستوى سطح البحر" أو استخدم بيانات METAR لأقرب مطار.
profile.info.title=الضغط عند مستوى سطح البحر
profile.label.seaLevelPressure=الضغط عند مستوى سطح البحر
profile.link.barometerTips=نصائح مستشعر البارومتر
profile.link.contactSupport=الاتصال بالدعم
profile.navigation.title=الملف الشخصي
profile.picker.units=الوحدات المفضلة
profile.region.unknown=منطقتك
profile.section.about=حول
profile.section.calibration=المعايرة
profile.section.support=الدعم
profile.section.units=الوحدات
profile.section.weatherKit=معايرة WeatherKit
profile.weatherKit.empty=اجلب بيانات الضغط المحلي للمعايرة التلقائية.
profile.weatherKit.latest=آخر قراءة
profile.weatherKit.summary.format=%@ • %@ • %@
session.chart.axis.pressure=الضغط
session.chart.axis.time=الوقت
session.chart.placeholder=سيظهر هذا المخطط بعد حفظ تسجيل.
session.chart.selected=لا شيء
session.chart.selected.detail.format=%@ • %@
session.chart.title.elevation=الارتفاع
session.chart.title.pressure=الضغط
session.notes.placeholder=أضف ملاحظات بعد مغامرتك القادمة لتتذكر الظروف.
session.notes.title=ملاحظات
session.overview.title=نظرة عامة
tab.altimeter.title=مقياس الارتفاع
tab.barometer.title=البارومتر
tab.profile.title=الملف الشخصي
trend.description.falling=الضغط في انخفاض
trend.description.rising=الضغط في ارتفاع
trend.description.steady=الضغط مستقر
units.imperial=النظام الإمبراطوري (قدم)
units.metric=النظام المتري (متر)
''')

# English fallback updates
en_update = parse_block('''
session.chart.selected=None
''')

# Spanish adjustments
es_update = parse_block('''
session.chart.selected=Ninguno
''')

es_mx_update = parse_block('''
session.chart.selected=Sin selección
''')

translation_map = {
    'zh-Hans': zh_hans,
    'ja': ja,
    'ko': ko,
    'de-DE': de,
    'fr-FR': fr,
    'pt-BR': pt_br,
    'ru': ru,
    'ar': ar,
    'es': es_update,
    'es-MX': es_mx_update,
}

path = Path('HowHigh/HowHigh/Localizable.xcstrings')
with path.open() as f:
    data = json.load(f)

strings = data['strings']

for key, entry in strings.items():
    locs = entry.setdefault('localizations', {})
    # ensure base English present
    if 'en' not in locs:
        value = en_update.get(key)
        if value is None:
            raise SystemExit(f"Missing base English for {key}")
        locs['en'] = {
            'stringUnit': {
                'state': 'translated',
                'value': value,
            }
        }
    en_value = locs['en']['stringUnit']['value']
    locs['en-GB'] = {
        'stringUnit': {
            'state': 'translated',
            'value': en_value,
        }
    }
    for lang, translations in translation_map.items():
        value = translations.get(key)
        if value is None:
            continue
        locs[lang] = {
            'stringUnit': {
                'state': 'translated',
                'value': value,
            }
        }

required = {'en', 'es', 'es-MX', 'en-GB', 'zh-Hans', 'ja', 'ko', 'de-DE', 'fr-FR', 'pt-BR', 'ru', 'ar'}
missing = {}
for key, entry in strings.items():
    locs = entry['localizations']
    missing_langs = sorted(lang for lang in required if lang not in locs)
    if missing_langs:
        missing[key] = missing_langs

if missing:
    raise SystemExit(f'Missing translations: {missing}')

path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
